### ISSUE TITLE
Test QAPipeline with GPU

### ISSUE THREAD

**Issue by n0thingLLM** [cdqa-suite/cdQA#115]
@fmikaelian 
I have implemented the changes as discussed. I tested the `fit()` method for the retriever and the `predict()` method in a notebook included in examples. Everything is working fine.

Could you please test the `fit()` method for the reader in GPU to check if everything is ok?

Please note that the current implementation of `QAPipeline` still uses the `TfidfRetriever` as you have implemented (passing the dataframe column as input to `TfidfRetriever.fit(df['content'])`). It should be changed once you will have implemented the improvement I proposed in #95.

_Originally posted by @andrelmfarias in https://github.com/fmikaelian/cdQA/pull/101#issuecomment-488628180_

**Comment by Swathygsb** [comment]
> I've been testing the training of the reader with `QAPipeline` on colab. It is working well, however due to GPU limitations I had to reduce the `batch_size` to 8 (the default is 32).
> 
> Code I used:
> 
> ```
> from cdqa.pipeline.cdqa_sklearn import QAPipeline
> qa_pipeline = QAPipeline(output_dir='./logs', train_batch_size=8, fp16=False)
> qa_pipeline.fit(X='data/train-v1.1.json', fit_reader=True)
> ```
> 
> @fmikaelian, please be attention that there is an error in the README about the training of the reader.
> It is written `cdqa_pipeline.fit(X=df, fit_reader=True)`.
> But for the reader we should not feed a dataframe as input, we should input a path to a json file in the SQUAD format (as mentioned in the docstring of `QAPipeline.fit()`).
> 
> Actually, I've been thinking about this and I think it is confusing to merge the training of the reader and the retriever in the same `fit()` method, because even if we pass an argument `fit_reader` the format of the argument `X` should be different for each of the modes.
> 
> In my opinion, I think we should have two separate training functions (as before): `fit()` and `fit_reader()`. I understand you want to be compliant with the scikit-learn package, but I don't think that including one more method (`fit_reader()`) will hurt the structure and compliance of our package.
> 
> What do you think about it?
Traceback (most recent call last):
  File "/home/ssathishbarani/Documents/cdqa/cdQA-master/dummy.py", line 29, in <module>
    qa_pipeline.fit(X='sec.json', fit_reader=True)
TypeError: fit() got an unexpected keyword argument 'fit_reader'

**Comment by fmikaelian** [comment]
Hi @Swathygsb 

There is no more boolean parameter `fit_reader` in the `fit()` method of the cdqa pipeline. Instead, we build a specific method `fit_reader()`.

If you want to fit both retriever and reader on your data, you can do:

```python
cdqa_pipeline.fit(X=df)
cdqa_pipeline.fit_reader(X='sec.json')
```
