### ISSUE TITLE
Support for SQuAD 2.0

### ISSUE THREAD

**Issue by fmikaelian** [cdqa-suite/cdQA#157]
- [ ] Train new pre-trained models on SQuAD 2.0

**Comment by thomasvn** [comment]
Hi!

Just curious but what are the specs for the machine used to fine-tune the model on SQuADv1.1 and SQuADv2.0?

How long did 1.1 take you? And how long do you think 2.0 will take you?

**Comment by andrelmfarias** [comment]
Hi @thomasvn, 

The fine-tuning of the Reader (BERT for QA) was run in an AWS EC2 p3.2xlarge machine (GPU Tesla V100 16GB). It took about 2 hours to complete (2 epochs on SQuAD 1.1 train was enough to achieve SOTA results on SQuAD 1.1 dev).

I think that 2 epochs on SQuAD 2.0 would take a little bit more than 3h

**Comment by thomasvn** [comment]
Awesome. Thanks for putting it into perspective!

**Comment by alex-movila** [comment]
there is already pretrained model [here](https://github.com/surbhardwaj/BERT-QnA-Squad_2.0_Finetuned_Model)
Could you adapt it fo cdQA?

**Comment by andrelmfarias** [comment]
Thanks @alex-movila, we will test this pre-trained model with cdQA and if it runs good we will probably integrate it to the package

**Comment by fmikaelian** [comment]
Closing this issue since it is part of the XLNet roadmap (PR #205, Issue #196)
