### ISSUE TITLE
Improve retriever model

### ISSUE THREAD

**Issue by fmikaelian** [cdqa-suite/cdQA#158]

**Comment by alex-movila** [comment]
"passage re-ranking with BERT" this may be too slow since it uses BERT

**Comment by alex-movila** [comment]
Here is some successful implementation. They use an ensemble of different algorithms combined with logistic regression. Could be useful for inspiration: 
https://allenai.org/aristo/

**Comment by andrelmfarias** [comment]
Hi @alex-movila thanks for indicating this project. However, as far as I am concerned, the Aristo model is only able to answer questions which have a small list of (usually 4 or 5) possible answers.

Our system is able to find answers for open questions, using a database of documents it can find the answer.

Then it's not useful for us.
