### ISSUE TITLE
exporting a model after fitting the data

### ISSUE THREAD

**Issue by Swathygsb** [cdqa-suite/cdQA#199]
how to export model after fitting the data?

cdqa_pipeline = QAPipeline(model='bert_qa_vCPU-sklearn.joblib')
cdqa_pipeline.fit_reader('sec.json')

Is there a way to save or export this cdqa pipeline?

**Comment by fmikaelian** [comment]
You should be able to do so with `joblib`:

```python
joblib.dump(cdqa_pipeline, os.path.join(output_dir, 'cdqa_pipeline.joblib'))
```

**Comment by Swathygsb** [comment]
_Hi @fmikaelian , 
After I have trained in the model (AWS EC2 pxlarge - GPU) and saved the pipeline, I tried to use the pipeline in my local (doesn't have GPU). I am not able to use it as such, as the model has been configured to run on GPU._

   raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location='cpu' to map your storages to the CPU.

**Comment by Swathygsb** [comment]
@fmikaelian 
Thanks. It works.

**Comment by Swathygsb** [comment]
Hi @fmikaelian, 
I tried my model in a GPU instance and saved the pipeline as you specified. But when i tried running the model in my local machine (doesnt have GPU), I am getting issues, as the model is adapted for running in a CUDA device. 

Loaded pipeline using the below code:
cdqa_pipeline = QAPipeline(reader=modelPath)
cdqa_pipeline.cpu()

**Comment by Swathygsb** [comment]
How to use a model trained using GPU to predict in local machines with only CPU?

**Comment by andrelmfarias** [comment]
Hi @Swathygsb,

After training a model on GPU, you should send it to CPU before dump it, because you cannot load a GPU model on a machine without GPU. There are two ways to do this:

1) Using Reader model (as per our [tutorial](https://github.com/cdqa-suite/cdQA/blob/master/examples/tutorial-train-reader-squad.ipynb)):
```
# Train model
reader.fit(X=(train_examples, train_features))

# Send it to CPU
reader.model.to('cpu')
reader.device = torch.device('cpu')

# Save it locally
joblib.dump(reader, os.path.join(reader.output_dir, 'reader_vCPU.joblib'))
```

2) Using the pipeline:
```
# Fit the model
cdqa_pipeline.fit_reader('squad-like-data.json')

# Send it to CPU
cdqa_pipeline.cpu()

# Save Reader model - CPU version
joblib.dump(cdqa_pipeline.reader, os.path.join(your_local_directory, 'reader_vCPU.joblib'))
```
