### ISSUE TITLE
Issue while Predicting

### ISSUE THREAD

**Issue by Swathygsb** [cdqa-suite/cdQA#200]
Tried fitting the model with data similar to SQUAD format 
cdqa_pipeline.fit_reader('sec.json')

Epoch: 100%|██████████| 3/3 [09:14<00:00, 186.53s/it]
Traceback (most recent call last):
  File "/home/ssathishbarani/Documents/cdqa/main.py", line 21, in <module>
    rs = cdqa_pipeline.predict(X='tell about t')
  File "/home/ssathishbarani/anaconda3/envs/cdqa/lib/python3.6/site-packages/cdqa/pipeline/cdqa_sklearn.py", line 122, in predict
    closest_docs_indices = self.retriever.predict(X, metadata=self.metadata)
AttributeError: 'QAPipeline' object has no attribute 'metadata'

**Comment by fmikaelian** [comment]
Hi @Swathygsb 

- The `fit()` method allows you to fine-tune the retriever of the cdqa pipeline. You use it on a pandas DataFrame containing your documents. See https://github.com/cdqa-suite/cdQA#manual
- The `fit_reader()` method allows you to fine-tune the reader of the cdqa pipeline. You use it on a JSON annotated dataset.

Can you try to add the following?

```python
cdqa_pipeline.fit(X=df)
```

Where `df` is the pandas DataFrame containing your documents.

You should then be able to do:

```python
cdqa_pipeline.predict(X='your question here')
```

**Comment by Swathygsb** [comment]
Even when I tried fitting the model with .csv file, I am getting the following error.

Completed reading csv file
  File "/home/ssathishbarani/anaconda3/envs/cdqa/lib/python3.6/site-packages/sklearn/feature_extraction/text.py", line 989, in _count_vocab
    raise ValueError("empty vocabulary; perhaps the documents only"
ValueError: empty vocabulary; perhaps the documents only contain stop words

Code:
df = pd.read_csv('data.csv')
print("Completed reading csv file")
cdqa_pipeline.fit(X=df)
print("completed fitting the model")

.csv file data:
date,title,category,link,abstract,paragraphs
14.05.2019,BNP Paribas at #VivaTech : discover the program of Saturday 18 May!,Innovation,https://group.bnpparibas/en/news/bnp-paribas-vivatech-discover-program-saturday-18-may,"From Thursday 16 to Saturday 18 May 2019, join us at Viva Technology on our Open Innovation Lab dedicated to Positive Banking: an experiential environment presenting 45 innovative projects developed by the Group in collaboration with start-ups.","['From may 16, 2019 to may 18, 2019', 'VivaTechnology 2019', 'Follow the event !', 'BNP Paribas at #VivaTech : discover the program of Friday 17 May!', 'From Thursday 16 to Saturday 18 May 2019, join us at Viva Technology on our Open Innovation Lab dedicated to Positive Banking: an experiential environment presenting 45 innovative projects developed by the Group in collaboration with start-ups.', 'Category', 'Throughout the general-public day on Saturday 18 May, our Lab will be entirely dedicated to youth and families around 5 major themes :', '10h30 - 11h30 : MAKE.ORG conference to announce the action plan of the civil society to give a chance to each young person-VivaTech stage, CEO Forum', '14h00 - 16h00 :“Next Startupper Challenge” An interscholastic competition with 10 universities participating to choose the most innovative start-up proposal made by students.-Pitch zone N°3, Hall 1', ""With Matthieu Jolly, Services & innovation manager at L'Echangeur by BNP Paribas Personal Finance"", '9h30 - 10h15', 'Entrepreneurship                                                                  Why should you finance your start-up with a crowdfunding campaign and how do you do so? WithSophie Reitzer, Fiona Picot et Gabriel Pimont-Nogues   ', '10h30 - 11h00', 'Future of Tech                                                                 Being impactful on Instagram. WithCéline Bécaud, Paul and Amelia Nymphea', '11h15 - 11h55', 'Furture of Tech                                                                  Tech is not rocket sicence! With Xavier Chanel', '12h10 - 12h25', 'Recruitment                                                                   Employer branding promises:""A sustainable and responsible global leader"". With Frédéric Auregan', '12h25 à 12h40', 'Recruitment                                                                   Employer branding promises: ""An open-minded Group"". With Lory Lopes and Audrey Debril   ', '13h00 à 13h30', 'Positive Impact / Youth                                                           BNP Paribas partners with innovative start-ups to support young people.WithFrancis Delchier and Benjamin Ducousso', '14h00 à 14h15', 'Recruitment                                                                   Employer branding promises: ""A learning company"". With Miguel Campos, Safaa Guennoun, Anne Cavalière and Nina Krankenberg ', '14h15 à 14h30', 'Recruitment                                                                   Employer branding promises: ""A place to work differently"". Anne Cavalière, Jérome Carré, Nina Krankenberg and Marine Pauthier', '14h45 à 15h30', 'Positive Impact / Youth                                                           Speed-mentoring session for young people. With Make.org', '15h45 à 16h30', 'Entrepreneurship                                                                 Why should you finance your start-up with a crowdfunding campaign and how do you do so? WithSophie Reitzer', 'Photo credits : ©Jean-Claude Guilloux', 'Share this page !', 'Tools', 'From May 24 to 26, 2018, BNP Paribas welcomes you to its Open Innovation Lab, labeled ""Positive...', 'From Thursday 16 to Saturday 18 May 2019, join us at Viva Technology on our Open Innovation Lab...', 'From Thursday 16 to Saturday 18 May 2019, join us at Viva Technology on our Open Innovation Lab...']"

**Comment by fmikaelian** [comment]
Hi @Swathygsb 

It seems the problems comes from the `paragraphs` column of your DataFrame. Each row of this column should contain a list of strings, where each string is a paragraph. Is it what you have?

**Comment by Swathygsb** [comment]
Hi @fmikaelian , 
I am using the data that has been shared in your github repo.

https://github.com/cdqa-suite/cdQA/releases/download/bnpp_newsroom_v1.1/bnpp_newsroom-v1.1.csv'

**Comment by andrelmfarias** [comment]
Hi @Swathygsb,

When you load the `bnpp_newsroom-v1.1.csv` as a dataframe you should set a converter `literal_eval`, so it will understand that the values in the column **paragraphs** are actually python lists. 
```
from ast import literal_eval

df = pd.read_csv('data/bnpp_newsroom_v1.1/bnpp_newsroom-v1.1.csv', converters={'paragraphs': literal_eval})
``` 

We can also refer to the example tutorials on the [examples repository](https://github.com/cdqa-suite/cdQA/tree/master/examples) or on [colab](https://colab.research.google.com/github/cdqa-suite/cdQA/blob/master/examples/tutorial-first-steps-cdqa.ipynb#scrollTo=nmmPPMIyLpH7)

There is also links to the notebooks on binder, you can check out the readme for all links to our tutorials.

**Comment by Swathygsb** [comment]
Hi @andrelmfarias , 
I tried using that as well. When I am trying to using the *bert GPU model, I am getting the following error. Is the model file corrupted by any chance?
---------------------------------------------------------------------------
EOFError                                  Traceback (most recent call last)
<ipython-input-14-d0fd553ca3e4> in <module>()
----> 1 cdqa_pipeline = QAPipeline(reader='bert_qa_vGPU-sklearn.joblib')

3 frames
/usr/lib/python3.6/pickle.py in load(self)
   1046                 key = read(1)
   1047                 if not key:
-> 1048                     raise EOFError
   1049                 assert isinstance(key, bytes_types)
   1050                 dispatch[key[0]](self)

EOFError:

**Comment by andrelmfarias** [comment]
Can you please run the following code and see if you still get errors? (Loading the CPU model and sending it to GPU)
```
cdqa_pipeline = QAPipeline(reader='bert_qa_vCPU-sklearn.joblib')
cdqa_pipeline.cpu()
```

**Comment by Swathygsb** [comment]
Thanks, it works :)

**Comment by andrelmfarias** [comment]
Perfect! Maybe the GPU model we released is actually corrupted... I will check it and fix it.

Thanks

**Comment by amit-shinde6** [comment]
I'm getting a different issue while using the predict function

query = 'Since when does the Excellence Program of BNP Paribas exist?'
prediction = cdqa_pipeline.predict(X=query)


Error : 


D:\Anaconda3\envs\py36\lib\site-packages\torch\nn\modules\module.py in __getattr__(self, name)
    533                 return modules[name]
    534         raise AttributeError("'{}' object has no attribute '{}'".format(
--> 535             type(self).__name__, name))
    536 
    537     def __setattr__(self, name, value):

AttributeError: 'BertAttention' object has no attribute 'output_attentions'

**Comment by andrelmfarias** [comment]
Hi @amit-shinde6 
It seems your issue is related to PyTorch or to BERT. 

Are you using the pre-trained models we provided?

**Comment by UMaa69** [comment]
df = pd.read_excel('/content/drive/My Drive/Cdqa demo data.xlsx', converters={'Paragraphs': literal_eval})

#df = pd.read_csv('./data/bnpp_newsroom_v1.1/bnpp_newsroom-v1.1.csv', converters={'paragraphs': literal_eval})
df = filter_paragraphs(df)
df.head()


File "<unknown>", line 1
    [The history of Agriculture in India dates back to Indus Valley Civilization and even before that in some places of Southern India. India ranks second worldwide in farm outputs. As per 2016, agriculture employed 49.9% of the Indian work force and contributed 16.9–17.9% to country's GDPIn 2016, agriculture and allied sectors like animal husbandry, forestry and fisheries accounted for 15.4% of the GDP (gross domestic product) with about 31% of the workforce in 2014.  India ranks first in the world with highest net cropped area followed by US and China. The economic contribution of agriculture to India's GDP is steadily declining with the country's broad-based economic growth. Still, agriculture is demographically the broadest economic sector and plays a significant role in the overall socio-economic fabric of India.]
               ^
SyntaxError: invalid syntax


It showingn this error .....plz tell me the way to sort out ( iam using my own data set it contains Title, category, Paragraphs . ) How can i read the data .
