### ISSUE TITLE
Is there a BERT - Cased model - pipeline available?

### ISSUE THREAD

**Issue by Swathygsb** [cdqa-suite/cdQA#207]
Bert CPU model which is available in your download.py seems to be uncased model. Do you have pipeline - pre trained on BERT cased models?

Issue:
The pre-trained model you are loading is an uncased model but you have set `do_lower_case` to False. We are setting `do_lower_case=True` for you but you may want to check this behavior.

**Comment by andrelmfarias** [comment]
We do not provide a cased version of BERT trained on SQuAD, as usually uncased versions are expected to perform better.

But, if you wish, you can train a cased version of the model. You just have to set the parameters `bert_model` to `bert-base-cased` and `do_lower_case` to False when creating the `BertQA` and `BertProcessor` instances.

**Comment by fmikaelian** [comment]
You can use the following notebook as a starting place to train your own BERT QA with custom params:

https://github.com/cdqa-suite/cdQA/blob/master/examples/tutorial-train-reader-squad.ipynb
