### ISSUE TITLE
How use pytorch fine tunned model

### ISSUE THREAD

**Issue by marcoaleixo** [cdqa-suite/cdQA#220]
I actually has a fine tunned pytorch model, is it possible to use that model?

**Comment by andrelmfarias** [comment]
Is your pytorch model a version of BERT?

**Comment by marcoaleixo** [comment]
Yes!

**Comment by andrelmfarias** [comment]
Did you trained your BERT model as proposed in our [tutorial](https://github.com/cdqa-suite/cdQA/blob/master/examples/tutorial-train-reader-squad.ipynb) and do you have a `.joblib` version of the model?

Or did you train using pure PyTorch and have a `.bin` and a `.config` file ?

**Comment by marcoaleixo** [comment]
I just have a .bin and .config file.

**Comment by andrelmfarias** [comment]
For now it is only possible to load a `.joblib` version as done in our tutorials, but we are currently working on a PR (#205) to include the option to load a Reader with `.bin` and `.config` files.

**Comment by marcoaleixo** [comment]
Nice!
I don't know if it's relevant, but maybe accept the .ckpt from tensorflow weights?

**Comment by andrelmfarias** [comment]
We do not use tf models, only pytorch models from Hugging Face

**Comment by marcoaleixo** [comment]
Ok!
