### ISSUE TITLE
CSV file conversion 

### ISSUE THREAD

**Issue by JimAva** [cdqa-suite/cdQA#234]
**Is your feature request related to a problem? Please describe.**
How to convert a CSV file to proper format?

**Describe the solution you'd like**
I have my own data in the [title, paragraphs] format.  However, paragraphs cells each contain one long string.  Is there a converter to break the string out into proper format for Training / Fine-tuning process (fit_reader). 

**Describe alternatives you've considered**
Is df2squad the proper converter?

**Additional context**

Here is the code that I'm using to convert my CSV file:
df = pd.read_csv('./data/train_dev.csv')
df = df2squad(df=df, squad_version='v1.1', output_dir='./data/', filename='train_dev')
df = filter_paragraphs(df)

I get the following error:
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-9-de4d1dfa7d71> in <module>()
      1 
----> 2 df = filter_paragraphs(df)
      3 #print('\nbefore 2 - \n', df.head())
      4 
      5 

/usr/local/lib/python3.6/dist-packages/cdqa/utils/filters.py in filter_paragraphs(articles, drop_empty, read_threshold, public_data, min_length, max_length)
     40 
     41     # Cleaning and filtering
---> 42     articles['paragraphs'] = articles['paragraphs'].apply(replace_and_split)
     43     articles['paragraphs'] = articles['paragraphs'].apply(filter_on_size)
     44     articles['paragraphs'] = articles['paragraphs'].apply(lambda x: x if len(x) > 0 else np.nan)

KeyError: 'paragraphs'

**Comment by fmikaelian** [comment]
Hi @JimAva 

You can only apply `filter_paragraphs()` on a Pandas DataFrame. That means you need to do this step before converting your dataframe in SQuAD-like JSON format. Here is an example:

```python
df = pd.read_csv('./data/train_dev.csv') # read CSV as Pandas DataFrame
df = filter_paragraphs(df) # Clean the DataFrame
df2squad(df=df, squad_version='v1.1', output_dir='./data/', filename='train_dev') # Export the DataFrame as JSON file usable with `fit_reader()`
```

**Comment by JimAva** [comment]
@fmikaelian - Thank you very much for the help.  FYI - I used the python textwrap to format my data properly for the DataFrame.  Then I ran cdqa_pipeline.fit_retriever(X=df) successfully and was able to run a few predictions.  

Another question, is running the fit_reader() necessary in this case?  When is it necessary to run fit_reader()?

**Comment by andrelmfarias** [comment]
Hi @JimAva ,

`fit_reader()` is used only if you want to fine-tune the BERT model on your custom **annotated** data. For that, you will need a dataset in the same format as SQUAD with samples of QA pairs and paragraphs.

If you don't need to fine-tune the model on your data, you won't need to use this method

**Comment by ayush-raj7** [comment]
I have a dataset with QA pairs and paragraphs. How can I convert it to squad 2.0 json like format so that i can fine-tune the reader.

**Comment by angelopf** [comment]
Same issue, I also cant figure out how to convert an already-annotated dataframe to squad 2.0 JSON. Thanks
