### ISSUE TITLE
No internet issue

### ISSUE THREAD

**Issue by Harudori** [cdqa-suite/cdQA#235]
I tried to run cdQA with the provided notebook example. The problem is : I can't have an internet access from where I run the code so it doesn't work because bert model is downloaded via an aws link.
`
Model name 'bert-base-uncased' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese). We assumed 'https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt' was a path or url but couldn't find any file associated to this path or url.
`

I tried to download Bert manually, go into the code and change the BertProcessor initialization, so that I can load Bert from a given path and it worked !

```python
class BertProcessor(BaseEstimator, TransformerMixin):
    def __init__(self,
        bert_model='path_to_model', # code change
        do_lower_case=True,
        is_training=False,
        version_2_with_negative=False,
        max_seq_length=384,
        doc_stride=128,
        max_query_length=64,
        verbose=False):
```

It would be great to have a parameter in the QAPipeline class where we can put this path, what do you think ? \o/
Or maybe is there another way to do it properly ?

**Comment by fmikaelian** [comment]
Hi @Harudori 

Actually @thomasvn recently added a functionality to pass a custom tokenizer to `BertProcessor()`. Check [his PR](https://github.com/cdqa-suite/cdQA/pull/227/files).

That means you should be able to download the file manually and load it this way:

```python
train_processor = BertProcessor(bert_model='bert-base-uncased',
                                                      do_lower_case=True,
                                                      is_training=True,
                                                      tokenizer=CUSTOM_TOKENIZER_OBJECT)
```

Can you try and tell us if it worked for you?

**Comment by Harudori** [comment]
Hi @fmikaelian ,

Thank you for your reply !
Actually, I was already possible to do what I suggested in the first message. I just had to put the argument `bert_model='path/to/model'` in the QAPipeline object and it worked.
