### ISSUE TITLE
Fallback option in reader

### ISSUE THREAD

**Issue by chiquadrat** [cdqa-suite/cdQA#250]
Hello,
is there the possibility to implement a fallback option in the Reader, e.g., if a paragraph (answer) is predicted with a probability below a certain threshold? I would like to avoid answers that does not make sense.
Best, chiquadrat

**Comment by andrelmfarias** [comment]
Hi @chiquadrat, your issue is related to an already closed one (#195).

Please refer to the discussion we had there. Thanks!
