### ISSUE TITLE
deploy a cdQA REST API and getting error: AttributeError: 'QAPipeline' object has no attribute 'fit'

### ISSUE THREAD

**Issue by morningstar899** [cdqa-suite/cdQA#258]
**Describe the bug**
When I try to deploy a cdQA REST API by running code "FLASK_APP=api.py flask run -h 0.0.0.0", I got error as below. Does anyone know why?  Thanks! 
  _File "/App/cdQA/api.py", line 21, in <module>
    cdqa_pipeline.fit(X=df)
AttributeError: 'QAPipeline' object has no attribute 'fit'_ 

**To Reproduce**
Steps to reproduce the behavior, just follow below instruction:
https://github.com/cdqa-suite/cdQA#Deployment

**Comment by andrelmfarias** [comment]
Hi @morningstar899 ,
Thanks for pointing this out.
We merged some changes yesterday that changed the name of the method `fit` to `fit_retriever`. We had forgotten to update `app.py` to take this change into account.

I have just fixed it, so please update your version of `cdqa`.

**Comment by morningstar899** [comment]
> Hi @morningstar899 ,
> Thanks for pointing this out.
> We merged some changes yesterday that changed the name of the method `fit` to `fit_retriever`. We had forgotten to update `app.py` to take this change into account.
> 
> I have just fixed it, so please update your version of `cdqa`.

Hi, Andre       Thanks for the quick fix!
