### ISSUE TITLE
After deploy cdQA REST API, get error: The requested URL was not found on the server

### ISSUE THREAD

**Issue by morningstar899** [cdqa-suite/cdQA#260]
**Describe the bug**
After deploy a cdQA REST API successfully, try to  make requests to test your API. I have try both from outside  and insider (using HTTPie), both getting error, why? Below is the detail error. 
Run '_http localhost:5000/api query=='your question here_'
Then get error: '_The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again._'
Check server console, error showing: 
_'204.40.194.136 - - [19/Sep/2019 18:14:14] "GET /api%20query=='your%20question%20here' HTTP/1.1" 404 -
204.40.194.136 - - [19/Sep/2019 18:14:14] "GET /favicon.ico HTTP/1.1" 404 -'_

**To Reproduce**
Steps to reproduce the behavior, just follow below instruction:
https://github.com/cdqa-suite/cdQA#Deployment

**Comment by andrelmfarias** [comment]
I just found out that our documentation is not correct. We are sorry for that, I will update the readme accordingly.
 
You should do as follow (no path should not contain " or '):
```
export dataset_path=path-to-dataset.csv
export reader_path=path-to-reader-model

FLASK_APP=api.py flask run -h 0.0.0.0
```

**Comment by Toronto899** [comment]
> I just found out that our documentation is not correct. We are sorry for that, I will update the readme accordingly.
> 
> You should do as follow (no path should not contain " or '):
> 
> ```
> export dataset_path=path-to-dataset.csv
> export reader_path=path-to-reader-model
> 
> FLASK_APP=api.py flask run -h 0.0.0.0
> ```

Hi, Andre     Thank your reply.    I just re-try (not contain " or '), still same error: 
99.228.83.88 - - [20/Sep/2019 12:59:16] "GET /api%20query=='your%20question%20here' HTTP/1.1" 404 -
99.228.83.88 - - [20/Sep/2019 12:59:17] "GET /favicon.ico HTTP/1.1" 404 -

**Comment by andrelmfarias** [comment]
Can you please show your logs after running the app? You should get something as the following:
```
$ FLASK_APP=api.py flask run -h 0.0.0.0
 * Serving Flask app "api.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
```

**Comment by Toronto899** [comment]
$ FLASK_APP=api.py flask run -h 0.0.0.0
 * Serving Flask app "api.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)

**Comment by Toronto899** [comment]
Hi, Andre   Above is the server log right after I run "FLASK_APP=api.py flask run -h 0.0.0.0", FYI, thanks!

**Comment by andrelmfarias** [comment]
And what do you get after running the query (i.e. `http localhost:5000/api query=='your question here'`

**Comment by Toronto899** [comment]
Nothing, it just wait over 30 seconds and then time out.     At sametime, on server console: 
99.228.83.88 - - [20/Sep/2019 12:59:16] "GET /api%20query=='your%20question%20here' HTTP/1.1" 404 -
99.228.83.88 - - [20/Sep/2019 12:59:17] "GET /favicon.ico HTTP/1.1" 404 -

**Comment by andrelmfarias** [comment]
Weird... I don't understand what might be the problem. I am getting that in my local machine:
```
127.0.0.1 - - [20/Sep/2019 15:08:15] "GET /api?query=your+question+here HTTP/1.1" 200 -
```

**Comment by Toronto899** [comment]
Hi, Andre,  thanks for looking for it.    This is I run from command line "xiaodong_cai899@linux-20190918:~$ http localhost:5000/api query=='your question here'
http: error: Request timed out (30s).";

This is what I got from server console " * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [20/Sep/2019 13:44:08] "GET /api?query=your+question+here HTTP/1.1" 200 -"

**Comment by andrelmfarias** [comment]
It seems the app is running ok, it outputs 200 in response.

It might be something related to the request HTTP.

@fmikaelian do you have any ideas what might be the issue?

**Comment by andrelmfarias** [comment]
Maybe the model is taking more than 30s to run (when running in CPU inference takes around 10 to 20s) and the http request times out before getting the output form the model

**Comment by Toronto899** [comment]
> Maybe the model is taking more than 30s to run (when running in my CPU, inference takes around 10 to 20s) and the http request times out before getting the output form the model

So, where we can modify the setting, so the http request time can be longer? Thanks!

**Comment by andrelmfarias** [comment]
> Maybe the model is taking more than 30s to run (when running in my CPU, inference takes around 10 to 20s) and the http request times out before getting the output form the model

It's definitely that, I just included a time.sleep(10) in the script `api.py` and the request timed out.

> So, where we can modify the setting, so the http request time can be longer? Thanks!

from a quick google search: https://httpie.org/doc#scripting  😊

**Comment by Toronto899** [comment]
> time.sleep(
Hi, Andre
May I confirm which line you add "time.sleep(10)" to api.py?  Thanks! 
_https://github.com/cdqa-suite/cdQA/blob/master/api.py_

**Comment by Toronto899** [comment]
> I just included a time.sleep(10) in the script `api.py`
Hi, Andre
May I know which line you add in  "time.sleep(10)" in the script api.py ?  Thanks! 
_https://github.com/cdqa-suite/cdQA/blob/master/api.py_

**Comment by andrelmfarias** [comment]
> May I know which line you add in "time.sleep(10)" in the script api.py ? Thanks!
https://github.com/cdqa-suite/cdQA/blob/master/api.py

I just did it locally for my testing. I won't be pushing this change to the repo as it doesn't make sense to add 10s of delay for other users
