### ISSUE TITLE
AttributeError: module 'torch._utils' has no attribute '_rebuild_parameter'

### ISSUE THREAD

**Issue by bhupensinghpanwar** [cdqa-suite/cdQA#261]
while implementing the line below in Jupyter notebook,
cdqa_pipeline = QAPipeline(reader='./models/bert_qa_vCPU-sklearn.joblib')
cdqa_pipeline.fit_retriever(X=df)

i get the following error:
module 'torch._utils' has no attribute '_rebuild_parameter'
![Error](https://user-images.githubusercontent.com/6176720/65314989-f1de8880-dbb4-11e9-9290-6e2b57868f4d.jpg)

**Comment by andrelmfarias** [comment]
Are you using the last versions of `cdqa`, `pytorch` and `sklearn`?

I just ran this code in local and on a Colab notebook (https://colab.research.google.com/github/cdqa-suite/cdQA/blob/master/examples/tutorial-first-steps-cdqa.ipynb) and I wasn't able to replicate this error...

**Comment by bhupensinghpanwar** [comment]
The error got resolved. i actually was using older version of pytorch. so i updated it. 
The problem actually got resolved by updation alone, but it was still showing the error because i hadnt restarted my Jupyter Notebook.

thanks for help
