### ISSUE TITLE
Can't Install it in Windows Pycharm

### ISSUE THREAD

**Issue by vedaanth** [cdqa-suite/cdQA#264]
this is embarrassing. However, I can't install the package on my Pycharm. Also, I wanted to train the model using my own data set. Is it possible. If it is What should I convert it in PDF or JSON. 

![qa](https://user-images.githubusercontent.com/47405741/65370652-88d14080-dc9a-11e9-9167-368f8cfe449e.PNG)

**Comment by MapleFlora** [comment]
Did you tried by installing the package via Anaconda "pip install cdqa" ?
Also before you install please install pytorch package ? "conda install pytorch torchvision cudatoolkit=10.0 -c pytorch"

**Comment by vedaanth** [comment]
I did. However, I placed the file inside the folder. Then it started working. Now, there is another issue.

**Comment by andrelmfarias** [comment]
Hi @vedaanth it seems your issue is related to this one: https://github.com/pytorch/pytorch/issues/5858

I think you can solve it if you write in your code the following:
```
if __name__ == '__main__' :
    torch.multiprocessing.freeze_support()
    # run the rest of your code normally 
    ...
```

**Comment by vedaanth** [comment]
@andrelmfarias I tried. However, I am still facing the same issue. I will attach the code below. 
////////////////////////////////////////////////////////////
import os
import pandas as pd
from ast import literal_eval
import torchvision
import torchvision.transforms as transforms
from multiprocessing import Process, freeze_support
import torch
from cdqa.utils.converters import pdf_converter,df2squad
from cdqa.utils.filters import filter_paragraphs
from cdqa.pipeline.cdqa_sklearn import QAPipeline
from cdqa.utils.download import download_model
from cdqa.reader.bertqa_sklearn import BertProcessor


if __name__ == '__main__':
    torch.multiprocessing.freeze_support()

download_model(model='bert-squad_1.1', dir='./models')

def download_pdf():
    import os
    import wget
    directory = './data/pdf/'
    models_url = [
    
   'https://grdc.com.au/__data/assets/pdf_file/0023/293117/GRDC-GrowNotes-Vetch-Southern.pdf?utm_source=website&utm_medium=download_button&utm_campaign=pdf_download&utm_term=South&utm_content=Vetch%20Southern%20Region%20-%20GrowNotes' 
    ]

    print('\nDownloading PDF files...')

    if not os.path.exists(directory):
        os.makedirs(directory)
    for url in models_url:
        wget.download(url=url, out=directory)

#download_pdf()

df = pdf_converter(directory_path='./data/pdf/')
df.head()


cdqa_pipeline = QAPipeline(reader='models/bert_qa_vCPU-sklearn.joblib')
#, retrieve_by_doc=False ,predict_batch_size=64, verbose_logging=True


cdqa_pipeline.fit_retriever(X=df)

query = 'What is Field-Peas ?  '
prediction = cdqa_pipeline.predict(X=query)
print('query: {}'.format(query))
print('answer: {}'.format(prediction[0]))
print('title: {}'.format(prediction[1]))
print('paragraph: {}'.format(prediction[2]))

**Comment by vedaanth** [comment]
@andrelmfarias Its still showing the same issue. I will post the code below.

///////////////////////////////////////////////////////////////

import os
import pandas as pd
from ast import literal_eval
import torchvision
import torchvision.transforms as transforms
from multiprocessing import Process, freeze_support
import torch
from cdqa.utils.converters import pdf_converter,df2squad
from cdqa.utils.filters import filter_paragraphs
from cdqa.pipeline.cdqa_sklearn import QAPipeline
from cdqa.utils.download import download_model
from cdqa.reader.bertqa_sklearn import BertProcessor


if __name__ == '__main__':
    torch.multiprocessing.freeze_support()

download_model(model='bert-squad_1.1', dir='./models')

def download_pdf():
    import os
    import wget
    directory = './data/pdf/'
    models_url = [
     ]

    print('\nDownloading PDF files...')

    if not os.path.exists(directory):
        os.makedirs(directory)
    for url in models_url:
        wget.download(url=url, out=directory)

#download_pdf()

df = pdf_converter(directory_path='./data/pdf/')
df.head()


cdqa_pipeline = QAPipeline(reader='models/bert_qa_vCPU-sklearn.joblib')
#, retrieve_by_doc=False ,predict_batch_size=64, verbose_logging=True


cdqa_pipeline.fit_retriever(X=df)

query = 'What is Field-Peas ?  '
prediction = cdqa_pipeline.predict(X=query)
print('query: {}'.format(query))
print('answer: {}'.format(prediction[0]))
print('title: {}'.format(prediction[1]))
print('paragraph: {}'.format(prediction[2]))
//////////////////////////////////////////////////////////

**Comment by andrelmfarias** [comment]
@vedaanth 

Is all your code running inside the `main`?
It doesn't seem it is...

**Comment by vedaanth** [comment]
@andrelmfarias sorry for that. I kind of posted the old code. The current code works. However, can you please tell me how can train this with my dataset. Since, I have pdf files and squad dataset is in json format.

**Comment by andrelmfarias** [comment]
@vedaanth ,

You can follow all the steps for training, prediction and pdf conversion on our README

**Comment by andrelmfarias** [comment]
I am closing this issue, as the problem with installation in windows seems to be solved.
