### ISSUE TITLE
Same error in the demo site: get "x.x.x.x:8080 says Error: Network Error" 

### ISSUE THREAD

**Issue by Toronto899** [cdqa-suite/cdQA#267]
Can someone look at the this issue("https://github.com/cdqa-suite/cdQA-ui/issues/11")?  Same error showing up in the demo site("https://cdqa-suite.github.io/cdQA-website/#demo") as well, FYI, thanks!

**Comment by andrelmfarias** [comment]
Closing the issue here, as the discussion is being done on cdqa-suite/cdQA-ui#11
