### ISSUE TITLE
Error in predictions with model trained on SQuAD_2.0.

### ISSUE THREAD

**Issue by SuyashSrivastavaDel** [cdqa-suite/cdQA#270]
Hey @andrelmfarias , I am facing a `Object of type ndarray is not JSON serializable` error while trying to predict with a model trained on SQuAD 2.0. This is after I integrated the recent changes in the code as the same model was working prior to the changes.

The traceback leads to the line:
`
TypeError                                 Traceback (most recent call last)
<ipython-input-10-da1f92b1705a> in <module>
----> 1 cdqa_pipeline.predict(query='What are the types of letters available?',n_predictions=5)

~/work/my_cdqa/cdQA/cdqa/pipeline/cdqa_sklearn.py in predict(self, query, n_predictions, retriever_score_weight, return_all_preds)
    184             n_predictions=n_predictions,
    185             retriever_score_weight=retriever_score_weight,
--> 186             return_all_preds=return_all_preds,
    187         )
    188         return prediction

~/work/my_cdqa/cdQA/cdqa/reader/bertqa_sklearn.py in predict(self, X, n_predictions, retriever_score_weight, return_all_preds)
   1500             self.null_score_diff_threshold,
   1501             retriever_score_weight,
-> 1502             n_predictions,
   1503         )
   1504 

~/work/my_cdqa/cdQA/cdqa/reader/bertqa_sklearn.py in write_predictions(all_examples, all_features, all_results, n_best_size, max_answer_length, do_lower_case, output_prediction_file, output_nbest_file, output_null_log_odds_file, verbose_logging, version_2_with_negative, null_score_diff_threshold, retriever_score_weight, n_predictions)
    809     if output_nbest_file:
    810         with open(output_nbest_file, "w") as writer:
--> 811             writer.write(json.dumps(all_nbest_json, indent=4) + "\n")
    812     if version_2_with_negative and output_null_log_odds_file:
    813         with open(output_null_log_odds_file, "w") as writer:
`

Digging a bit further I found, the `all_nbest_json` ordered dictionary which we try to get json dumps of, has keys :
-qas_id,
-title,
-paragraph,
-retriever_score,
-final_score,

Out of which retriever_score & final_score are numpy arrays.
 
Example of `all_nbest_json` just before writing its json dumps,
`
OrderedDict([('bf0ad31b-bc66-49a7-9ce1-58f22885a1fd', [{'text': 'Employment Verification-Only Letters', 'probability': 0.3392636887985102, 'start_logit': 3.865283489227295, 'end_logit': 2.52488374710083, 'qas_id': 'bf0ad31b-bc66-49a7-9ce1-58f22885a1fd', 'title': 'document-page-0-0.pdf', 'paragraph': 'The two types of employment verification letters are as follows: Employment Verification-Only Letters Employment Verifications Letters, including verifications of roles and responsibilities', 'retriever_score': array([10.61635125]), 'final_score': array([7.86933164])}, {'text': 'Employment Verification-Only Letters Employment Verifications Letters', 'probability': 0.2887090090055999, 'start_logit': 3.865283489227295, 'end_logit': 2.363525390625}, {'text': 'Employment Verification-Only Letters Employment Verifications', 'probability': 0.09489530787730506, 'start_logit': 3.865283489227295, 'end_logit': 1.2508803606033325}, {'text': 'Employment Verification-Only', 'probability': 0.06885599465677525, 'start_logit': 3.865283489227295, 'end_logit': 0.9301233887672424}, {'text': 'Employment Verifications Letters', 'probability': 0.06523055031844521, 'start_logit': 2.3777921199798584, 'end_logit': 2.363525390625}, {'text': '', 'probability': 0.02710271564773507, 'start_logit': 1.9641821384429932, 'end_logit': 1.898841381072998}])])

`
I understand this error is because the retriever_score and the final_score are numpy arrays.
Could you please help me with this?

**Comment by SuyashSrivastavaDel** [comment]
Hey @andrelmfarias , changing the following lines

https://github.com/cdqa-suite/cdQA/blob/759ff018852115f39304816575ad6efc427fa16f/cdqa/reader/bertqa_sklearn.py#L788-L791


to this 


        best_dict["retriever_score"] = example.retriever_score.tolist()
        best_dict["final_score"] = (
            (1 - retriever_score_weight) *
            (best_dict["start_logit"] + best_dict["end_logit"]) +
            retriever_score_weight * example.retriever_score).tolist()`

seems to solve the issue.
Let me know what you think about this.

**Comment by andrelmfarias** [comment]
Hi @SuyashSrivastavaDel, nice catch! 

I think your solution might work, but I prefer to keep it as a scalar number instead of a list with only one element, so you can replace `.tolist()` by `.item()` and I think it will be good.

Thanks!

**Comment by SuyashSrivastavaDel** [comment]
Hey @andrelmfarias ! Makes sense. Changed to `.item()`.

Thanks for your time!
