### ISSUE TITLE
Google Colab fit_retriever bug

### ISSUE THREAD

**Issue by sk38897** [cdqa-suite/cdQA#271]
Using Google Colab for trying out the PDF converter, I keep getting fit_retriever() got an unexpected keyword argument 'X', prior to executing a query.

**Comment by ahotrod** [comment]
Try `cdqa_pipeline.fit_retriever(df = df)`

**Comment by sk38897** [comment]
Thank you it worked. Is there a way to run CdQA with custom datasets and models in Colab for quick testing ? Sorry for posting the Q here.

**Comment by andrelmfarias** [comment]
You can take a look at our tutorials for quick testing here:

https://github.com/cdqa-suite/cdQA#notebook-examples
