### ISSUE TITLE
How to prepare the BNP dataset

### ISSUE THREAD

**Issue by morningstar899** [cdqa-suite/cdQA#274]
I am wondering how the BNP dataset be prepare, look like there are some kind of web-scraping to do that?  Could you please share that tools as well?  Thanks!

**Comment by fmikaelian** [comment]
Hi @morningstar899 

We used the following script to get the data: https://github.com/cdqa-suite/cdQA/blob/88a1ff2bb249f24edc427737ccb0b8f8959cf0b6/cdqa/scrapper/bs4_bnpp_newsroom.py
