### ISSUE TITLE
Questions on a HuggingFace's issue

### ISSUE THREAD

**Issue by andrelmfarias** [cdqa-suite/cdQA#275]
Some questions asked on an issue on the HuggingFace repository by @rsomani95 (https://github.com/huggingface/transformers/issues/332)

> Hi @andrelmfarias, thank you for sharing this great resource!
> 
> The cdQA-suite seems to cater to a specific kind of question answering, as described in your Medium article. To summarise, it looks for the answer to a question from a collection of documents -- all these documents most likely contain different kinds of information regarding a particular topic. For example, a system built using cdQA could contain 10 different documents regarding 10 different historical periods, and you could ask it a question about any of these time periods, and it would search for the relevant answer within these 10 documents.
> 
> However, if the system you want to build is such: you have 10 court orders, and you want to ask the system the same set of questions for each court order. For example:
> 
> When was the order filed?
> Who filed the order?
> Who was the order filed against?
> Was there a settlement?
> In this case, I wouldn't want the system to search through every document, but instead look for answers within the document itself. Exactly like SQuaD 2.0.
> My assessment is that I wouldn't be able to build such a system using cdQA but I could use the cdQA annotator to build my dataset. Is that a sound assessment?
> 
> Also, I'm curious to hear your thoughts on how feasible it would be to expect good results when the context is rather long (anywhere between 2-10 pages).
> Thank you :)

**Comment by andrelmfarias** [comment]
My answers for the questions below:

> However, if the system you want to build is such: you have 10 court orders, and you want to ask the system the same set of questions for each court order. For example:
> 
> When was the order filed?
> Who filed the order?
> Who was the order filed against?
> Was there a settlement?
> In this case, I wouldn't want the system to search through every document, but instead look for answers within the document itself

This a very good question. On way to deal with this kind of situation would be to have in each document some sort of identification, date or time that differs the documents and to specify these on the questions. When the Retriever computes the similarity of your question and the documents it's probably going to give a higher score to the documents that have the same id, date or time in your question. The final score for ranking is obtained with a combination of the Reader score and Retriever score, so in the end, you probably will get the answer from the document you want, but you **should have one or more strings that differ the document from on another and specify it in the question**.
To be honest, I did not test this case and don't know how efficient it is, but from a theoretical standpoint, it should work.

> Also, I'm curious to hear your thoughts on how feasible it would be to expect good results when the context is rather long (anywhere between 2-10 pages).
> Thank you :)

As explained in the article, **the documents are divided into paragraphs** and each of these is sent to the Reader (`BertForQuestionAnswering` model in this case) together with the question and the Reader outputs an answer for each pair question-paragraph with a score. In the end, the system ranks the answers by combining the Reader and Retriever scores.
So no matter the size of the document (it can have 1 paragraph, 10 pages, or 10k pages), the system will always be able to split it into smaller paragraphs.

I hope I answered your questions 😊

**Comment by lewtun** [comment]
> However, if the system you want to build is such: you have 10 court orders, and you want to ask the system the same set of questions for each court order. For example:
> 
> When was the order filed?
Who filed the order?
Who was the order filed against?
Was there a settlement?
In this case, I wouldn't want the system to search through every document, but instead look for answers within the document itself

Instead of linking documents to questions by some common ID (as @andrelmfarias suggested), why not create a DataFrame `articles_df` of articles (as normal), loop over queries, and generate predictions per article?

In pseudo-code:

```python
from cdqa.utils.converters import pdf_converter
from cdqa.pipeline import QAPipeline

articles_df = pdf_converter(directory_path='path/to/articles/')

n_preds = 3

queries = ['When was the order filed?', ...]

qa_pipeline = QAPipeline(
    reader="../models/bert_qa_vCPU-sklearn.joblib", retrieve_by_doc=False, top_n=20, verbose=False
)

for q in queries:
    for title in articles_df['title']:
        qa_pipeline.fit_retriever(X=articles_df.query(f"title == '{title}'"))
        prediction = qa_pipeline.predict(X=q, n_predictions=n_preds)
        print(f'\nQuery: {q}')
        print(f'Predictions for article {title} ...\n')
        print(prediction)
```

Perhaps it does not make sense to fit the retriever on a single article, but some small experiments I did with the above gave reasonable results on my dataset.
