### ISSUE TITLE
Try to use "bert_qa_vGPU-sklearn.joblib" and getting error

### ISSUE THREAD

**Issue by morningstar899** [cdqa-suite/cdQA#277]
**Describe the bug**
Try to use "export reader_path=/home/xxxxxx/bert_qa_vGPU-sklearn.joblib" and bring server up by "FLASK_APP=api.py flask run -h 0.0.0.0", when I try to use "http localhost:5000/api query=='What are the activities of BNP Paribas?'" , then on client site getting error: 
_"500 Internal Server Error"_
Console site:    
_"File "/App/cdQA/cdqa/reader/bertqa_sklearn.py", line 1499, in predict
    os.makedirs(self.output_dir)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: 'models'"_

BTW, using "export reader_path=/home/xxxxxx/bert_qa_vCPU-sklearn.joblib" is fine. FYI, thanks!

**Comment by andrelmfarias** [comment]
Hi @morningstar899 ,

I think the GPU model wasn't up to date. I just uploaded a new version that is up to date with the CPU version.

Could you please try it again and tell me if it works?

Thanks

**Comment by morningstar899** [comment]
> Hi @morningstar899 ,
> 
> I think the GPU model wasn't up to date. I just uploaded a new version that is up to date with the CPU version.
> 
> Could you please try it again and tell me if it works?
> 
> Thanks

Hi, Andre      Yes, it work very well, great work!
