### ISSUE TITLE
Any plans to adding ALBERT?

### ISSUE THREAD

**Issue by maxbaluev** [cdqa-suite/cdQA#296]
You can find it there https://github.com/google-research/google-research/tree/master/albert

**Comment by andrelmfarias** [comment]
Hi @maxbaluev ,

Our library is built on top of the Hugging Face's [transformers](https://github.com/huggingface/transformers) library and we use pre-trained QA models released by them.

For now, they haven't added ALBERT do their repo yet, so it is not in our roadmap either.

**Comment by maxbaluev** [comment]
@andrelmfarias but work in progress https://github.com/huggingface/transformers/pull/1683 and albert v2 much better.
