### ISSUE TITLE
No module named 'transformers'

### ISSUE THREAD

**Issue by TobiKoledoye** [cdqa-suite/cdQA#301]
I tried using the new pretrained model "bert_qa.joblib" the error its giving is 

"No module named 'transformers'" 

What can i do about this?

**Comment by andrelmfarias** [comment]
Hi,

Which version of cdQA are you using? The model only works with the last version

**Comment by TobiKoledoye** [comment]
The recent cdQA. I newly pip installed it.

**Comment by andrelmfarias** [comment]
Could you please pip install it again?

The model `bert_qa.joblib` was built for a dev branch that was merged yesterday.

There were some important changes with this merge, notably the import from `transformers` instead of the previous import from `pytorch_pretrained_bert`

**Comment by andrelmfarias** [comment]
Btw, both models are pretty much the same, the new `bert_qa.joblib` was just released to be compatible with the last changes in the library

**Comment by TobiKoledoye** [comment]
Thanks, i will do that right away. will give you feedback.
