### ISSUE TITLE
Unable to convert PDF to cdqa dataframe

### ISSUE THREAD

**Issue by SmritiSatyan** [cdqa-suite/cdQA#311]
Hello, 
I am following the steps from the link 'https://github.com/cdqa-suite/cdQA'. When I try with the BNparibas dataset, everything works fine. Now I wish to create my own dataset. Instead of manually creating one, I decided to go with 'converters' and use the 'pdf_converter' from utils.py file to convert my pdf into a dataframe. But I am unable to generate the dataframe using the code:
```
from cdqa.utils.converters import pdf_converter
df = pdf_converter(directory_path='path_to_pdf_folder')
```
Here 'path_tp_pdf_folder' holds the path where my pdf file is stored. This is assigned to a variable named 'df', I tried displaying 'df' on the console and it just shows 2 lines. 
Any suggestions on this would be great. 
I am using Windows OS

**Comment by andrelmfarias** [comment]
Hi @SmritiSatyan ,

How many pdf files do you have in your directory? Our `pdf_converter` considers each pdf to be one document, so the dataframe will have one line per document with all the paragraphs in a list ain the column `paragraphs`.

**Comment by SmritiSatyan** [comment]
Hello @andrelmfarias , Yes my directory has just one PDF document. I understood the concept now. Thank you so much.
