### ISSUE TITLE
'BertConfig' object has no attribute 'is_decoder'

### ISSUE THREAD

**Issue by cyberandy** [cdqa-suite/cdQA#313]
**Here is the bug**
![image](https://user-images.githubusercontent.com/837037/69750241-95678e80-114c-11ea-9dc8-74aa0a7c51a6.png)

**To Reproduce**
1. Go to 'tutorial-first-steps-cdqa.ipynb' using Google Colab
2. Run the notebook 
3. Execute the query 

**Additional context**
Yesterday it worked just fine, I checked again the examples from here to make sure it wasn't a problem with my code (link from here: https://github.com/cdqa-suite/cdQA#notebook-examples). Is there something related to the latest update of the transformers?

Many thanks for your kind help

**Comment by andrelmfarias** [comment]
Hi @cyberandy,

Maybe this is related to their latest release, I will debug it later. For now, you can use `DistilBert`, I just tested on colab and worked fine.

Change the download and loading lines to:
```
download_model(model='distilbert-squad_1.1', dir='./models')
```
```
cdqa_pipeline = QAPipeline(reader='./models/distilbert_qa.joblib')
```

**Comment by cyberandy** [comment]
Thanks @andrelmfarias, works just fine with distilbert and I will wait for your debug. Congratulation for the project!

**Comment by andrelmfarias** [comment]
I have just uploaded a new model `bert_qa` with the bug fixed, the colab notebook is working with BERT now
