### ISSUE TITLE
NotFittedError-while evaluating models

### ISSUE THREAD

**Issue by SandhyaSuryanarayana** [cdqa-suite/cdQA#318]
I have created a custom squad like dataset using annotator. 
while evaluating the json file I'm getting the below error.  
Any help is appreciated.

![Error](https://user-images.githubusercontent.com/21112063/70013130-a0536200-1544-11ea-82a1-290807200e5e.png)

**Comment by andrelmfarias** [comment]
Hi,

You have to fit the pipeline retriever to the dataframe with the documents before calling the `evaluate_pipeline` function
