### ISSUE TITLE
Unable to deploy cdQA REST API 

### ISSUE THREAD

**Issue by SmritiSatyan** [cdqa-suite/cdQA#331]
I am following the deployment section of 'https://github.com/cdqa-suite/cdQA/blob/master/README.md' link. I am using Windows and hence using the 'set' keyword instead of the 'export' keyword. Once I run the `flask -h 0.0.0.0`, I get errors like "ERR_EMPTY_RESPONSE", "Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.". I am unable to understand why this error is showing up. 
On the command line, my log says `[03/Jan/2020 17:16:11] "GET /api%20query=='ac%20not%20cooling' HTTP/1.1" 404 -`
I tried using my ipV4 address, 0.0.0.0:5000/api query=='ac not cooling' and 127.0.0.1:5000/...
Nothing seems to help. 
Any help on this would be very much helpful.

**Comment by af994ea7-d54f-4f1a-b5d2-c1537cabc29b** [comment]
**Hey!** @SmritiSatyan 
you are sending the request to 
> /api%20query==

rather than sending it to

> /api?query==

Hope this helps.
