### ISSUE TITLE
cdqa install error

### ISSUE THREAD

**Issue by alikabeer32** [cdqa-suite/cdQA#361]
while intalling using 
`pip install cdqa`

I suddenly get this:
`Collecting tika==1.19
  Using cached tika-1.19.tar.gz (24 kB)
  WARNING: Requested tika==1.19 from https://files.pythonhosted.org/packages/10/75/b566e446ffcf292f10c8d84c15a3d91615fe3d7ca8072a17c949d4e84b66/tika-1.19.tar.gz#sha256=a1bac3eb54ea99b672dc1c097f7d10748748bf3a58e2def7a190fefed9c49324 (from cdqa), but installing version 1.24

ERROR: Could not find a version that satisfies the requirement torch==1.2.0 (from cdqa) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.2.0 (from cdqa)
`

**Comment by grosa1** [comment]
What version of python are you using?

**Comment by alikabeer32** [comment]
@grosa1 3.7 but I resolved it by installing torch 1.2.0 using:
`pip install torch==1.2.0 -f https://download.pytorch.org/whl/cu100/torch_stable.html`
